os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "9.8.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - crypto-pwa/node_modules
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g ionic@3.20.0
script:
  - chmod +x holdings-api/mvnw
  - cd holdings-api && ./mvnw clean test
  - cd ../crypto-pwa && npm test
  - cd ../holdings-api/mvnw spring-boot:run &
  - cd ../crypto-pwa && npm run build --prod
  - npm run e2e
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
